[default.extend-words]
# Intentional abbreviations/names
LOD = "LOD"
OT = "OT"
parms = "parms"
Parm = "Parm"
parm = "parm"
Teh = "Teh"
teh = "teh"
gattling = "gattling"
Gattling = "Gattling"
hight = "hight"
Hight = "Hight"
Mis = "Mis"
sav = "sav"
dout = "dout"
strat = "strat"
fpt = "fpt"
Fpt = "Fpt"
inout = "inout"
Inout = "Inout"
nd = "nd"
ND = "ND"
ba = "ba"
fo = "fo"
ser = "ser"
als = "als"
hel = "hel"
dif = "dif"
ang = "ang"
som = "som"
te = "te"
bu = "bu"
ot = "ot"
ist = "ist"
ehr = "ehr"
sur = "sur"
clen = "clen"

[files]
extend-exclude = [
    "*.rc",
    "*.resx",
    "*.vcproj",
    "*.vcxproj",
    "*.sln",
    "*.filters",
    "*.user",
    "*.ini",
    "*.map",
    "*.str",
    "*.csf",
    "Thirdparty/**",
    "docs/**",
]
